DROP DATABASE IF EXISTS TRABALHO;
-- 1 ) Um Banco de Dados chamado TRABALHO (0,1 ponto).--

CREATE DATABASE IF NOT EXISTS TRABALHO;

 /* 2 ) Com base no diagrama da figura 1, faça o script em Linguagem SQL para os SGBDs
MySQL/MariaDB que crie todas as tabelas no banco de dados TRABALHO (0,9 ponto).
◦ As chaves primárias e chaves estrangeiras devem estar inseridas no final dos
comandos
◦ Todas as constraints devem ser nomeadas, como feito em sala de aula. */

DROP TABLE IF EXISTS TRABALHO.ALUNO;
CREATE TABLE IF NOT EXISTS TRABALHO.ALUNO(
    RA          INT             NOT NULL AUTO_INCREMENT,
    NOME_ALUNO  VARCHAR(250)    NOT NULL,
    SEXO_ALUNO  VARCHAR(1)      NOT NULL COMMENT "F - FEMININO / M - MASCULINO",
    CONSTRAINT PK_ALUNO PRIMARY KEY (RA)
)ENGINE=INNODB;

DROP TABLE IF EXISTS TRABALHO.TURMA;
CREATE TABLE IF NOT EXISTS TRABALHO.TURMA(
    NUM_TURMA           INT  NOT NULL AUTO_INCREMENT,
    DTA_INICIO_AULAS    DATE NOT NULL,
    DTA_FIM_AULAS       DATE NOT NULL,
    CONSTRAINT PK_TURMA PRIMARY KEY (NUM_TURMA)
)ENGINE=INNODB;

DROP TABLE IF EXISTS TRABALHO.MATRICULA;
CREATE TABLE IF NOT EXISTS TRABALHO.MATRICULA(
    NUM_MATRICULA               INT     NOT NULL AUTO_INCREMENT,
    DTA_MATRICULA               DATE    NOT NULL,
    DTA_CANCELAMENTO_MATRICULA  DATE,
    RA                          INT     NOT NULL,
    NUM_TURMA                   INT     NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY (NUM_MATRICULA),
    CONSTRAINT FK_MATRICULA_2_RA
        FOREIGN KEY (RA)
            REFERENCES TRABALHO.ALUNO (RA),
    CONSTRAINT FK_MATRICULA_2_TURMA
        FOREIGN KEY (NUM_TURMA)
            REFERENCES TRABALHO.TURMA (NUM_TURMA)
)ENGINE=INNODB;


DROP TABLE IF EXISTS TRABALHO.DISCIPLINA;
CREATE TABLE IF NOT EXISTS TRABALHO.DISCIPLINA(
    COD_DISCIPLINA  INT             NOT NULL AUTO_INCREMENT,
    NOM_DISCIPLINA  VARCHAR(250)    NOT NULL,
    CARGA_HORARIA   INT             NOT NULL,
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (COD_DISCIPLINA)
)ENGINE=INNODB;

DROP TABLE IF EXISTS TRABALHO.PROFESSOR;
CREATE TABLE IF NOT EXISTS TRABALHO.PROFESSOR(
    MATRICULA       INT             NOT NULL AUTO_INCREMENT,
    NOME_PROFESSOR  VARCHAR(250)    NOT NULL,
    TITULACAO       VARCHAR(100)    NOT NULL,
    SEXO_PROFESSOR  VARCHAR(1)      NOT NULL COMMENT "F - FEMININO / M - MASCULINO",
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (MATRICULA)
)ENGINE=INNODB;

DROP TABLE IF EXISTS TRABALHO.DISCIPLINA_OFERECIDA;
CREATE TABLE IF NOT EXISTS TRABALHO.DISCIPLINA_OFERECIDA(
    NUM_DISCIPLINA_OFERECIDA    INT         NOT NULL AUTO_INCREMENT,
    SALA                        VARCHAR(10) NOT NULL,
    BLOCO                       VARCHAR(10) NOT NULL,
    DIA_SEMANA                  INT         NOT NULL COMMENT "DEVE SER ENTRE 1-DOMINGO E 7-SABADO",
    HOR_INICIO                  TIME        NOT NULL,
    HOR_FIM                     TIME        NOT NULL,
    MATRICULA                   INT         NOT NULL,
    NUM_TURMA                   INT         NOT NULL,
    COD_DISCIPLINA              INT         NOT NULL,
    CONSTRAINT PK_DISCIPLINA_OFERECIDA PRIMARY KEY (NUM_DISCIPLINA_OFERECIDA),
    CONSTRAINT FK_DISCIPLINA_OFERECIDA_2_TURMA
        FOREIGN KEY (NUM_TURMA)
            REFERENCES TRABALHO.TURMA (NUM_TURMA),
    CONSTRAINT FK_DISCIPLINA_OFERECIDA_2_DISCIPLINA
        FOREIGN KEY (COD_DISCIPLINA)
            REFERENCES TRABALHO.DISCIPLINA (COD_DISCIPLINA),
    CONSTRAINT FK_DISCIPLINA_OFERECIDA_2_PROFESSOR
        FOREIGN KEY (MATRICULA)
            REFERENCES TRABALHO.PROFESSOR (MATRICULA)
)ENGINE=INNODB;



DROP TABLE IF EXISTS TRABALHO.AVALIACAO;
CREATE TABLE IF NOT EXISTS TRABALHO.AVALIACAO(
    SEQ_AVALIACAO_ALUNO         INT             NOT NULL,
    NOTA_A2                     DECIMAL(5,2)    NOT NULL COMMENT "DEVE ESTAR ENTRE 0 E 5",
    NOTA_A1                     DECIMAL(5,2)    NOT NULL COMMENT "DEVE ESTAR ENTRE 0 E 5",
    NOTA_AF                     DECIMAL(5,2)    COMMENT "DEVE ESTAR ENTRE 0 E 5",
    RA                          INT             NOT NULL,
    NUM_DISCIPLINA_OFERECIDA    INT             NOT NULL,
    CONSTRAINT PK_AVALIACAO PRIMARY KEY (SEQ_AVALIACAO_ALUNO),
    CONSTRAINT FK_AVALIACAO_2_ALUNO
        FOREIGN KEY (RA)
            REFERENCES TRABALHO.ALUNO (RA),
    CONSTRAINT FK_AVALIACAO_2_DISCIPLINA_OFERECIDA
        FOREIGN KEY (NUM_DISCIPLINA_OFERECIDA)
            REFERENCES TRABALHO.DISCIPLINA_OFERECIDA (NUM_DISCIPLINA_OFERECIDA)
)ENGINE=INNODB;